name: ml-vis
channels:
  - defaults
dependencies:
  - bokeh=2.2           # For visualization
  - pip
  - python=3.7
  - scikit-learn=0.23   # For dimensionality reduction
  - tensorflow-gpu=2.2  # For neural networks
