name: ml-vis
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - cudnn=7.6
  - bokeh=2.2                # For visualization
  - pip=21.0
  - python=3.7
  - scikit-learn=0.23        # For dimensionality reduction
  - scipy=1.5                # For matrix reordering
  - umap-learn=0.5           # For dimensionality reduction
  - pip:
    - tensorflow-gpu==2.2.*  # For neural networks
