name: ml-vis
channels:
  - defaults
dependencies:
  - bokeh=2.2          # For visualization
  - pip
  - python
  - scikit-learn=0.23  # For dimensionality reduction
  - scipy=1.5          # For matrix reordering
  - tensorflow=2.2     # For neural networks
